### ISSUE TITLE
userParams

### ISSUE THREAD

**Issue by eleimt** [hcodes/lyam#8]
Здравствуй
Подскажи
```
const userVars = { myParam: 123 };
```
Это https://yandex.ru/support/metrica/objects/user-params.html?

**Comment by hcodes** [comment]
Это https://yandex.ru/support/metrica/objects/params-method.html

**Comment by hcodes** [comment]
Путаница возникает, поправлю `userParams` на `params`.

**Comment by eleimt** [comment]
А https://yandex.ru/support/metrica/objects/user-params.html можно ожидать доработкой? Есть ли вожможность вообще?

**Comment by hcodes** [comment]
В ближайшем будущем скорее нет. Возможность не исследовал.

**Comment by eleimt** [comment]
Эх.. Буду ожидать появленения. Благодарю за пакет.

**Comment by eleimt** [comment]
Жесть как жду, очень надо :)
Спасибо.

**Comment by hcodes** [comment]
v2.0.0
